spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  application:
    name: journalApp
#  data:
#    mongodb:
#      host: localhost
#      port: 27017

server:
  port: 8080